anchor_version = "0.25.0"
solana_version = "1.10.41"

[programs.localnet]
voter_stake_registry = "vsrZ1Nfkxmt1hVaB7ftvcj7XpRoQ1YtCgPLajeaV6Uj"

[programs.devnet]
voter_stake_registry = "vsrZ1Nfkxmt1hVaB7ftvcj7XpRoQ1YtCgPLajeaV6Uj"

[programs.mainnet]
voter_stake_registry = "vsrZ1Nfkxmt1hVaB7ftvcj7XpRoQ1YtCgPLajeaV6Uj"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[workspace]
members = ["programs/voter-stake-registry"]